services:
  api_policy:
    container_name: api_policy
    build: .
    # command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 5000 --reload"
    ports:
      - 3813:5000
    networks:
      - network_policy
    depends_on:
      - mongodb_policy

  mongodb_policy:
    container_name: mongodb_policy
    image: mongo:latest
    restart: always
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - network_policy

  rabbitmq_policy:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq_policy"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=policy
      - RABBITMQ_DEFAULT_PASS=policy123
    networks:
      - network_policy

networks:
  network_policy:
    driver: bridge
    name: policy-networks
