"""create_tables

Revision ID: c987be9d1289
Revises: 
Create Date: 2023-06-03 18:49:31.430609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c987be9d1289'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('street', 'number')
    )
    op.create_index(op.f('ix_address_number'), 'address', ['number'], unique=False)
    op.create_index(op.f('ix_address_street'), 'address', ['street'], unique=False)
    op.create_table('beneficiary',
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('document', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('beneficiary_id')
    )
    op.create_index(op.f('ix_beneficiary_beneficiary_id'), 'beneficiary', ['beneficiary_id'], unique=False)
    op.create_table('product_details',
    sa.Column('product_details_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.Integer(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('plate', sa.String(), nullable=True),
    sa.Column('chassi', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('product_details_id')
    )
    op.create_index(op.f('ix_product_details_product_details_id'), 'product_details', ['product_details_id'], unique=False)
    op.create_table('renter',
    sa.Column('renter_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('document', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('renter_id')
    )
    op.create_index(op.f('ix_renter_renter_id'), 'renter', ['renter_id'], unique=False)
    op.create_table('policy',
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('beneficiary_id', sa.Integer(), nullable=False),
    sa.Column('renter_id', sa.Integer(), nullable=True),
    sa.Column('product_details_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.beneficiary_id'], ),
    sa.ForeignKeyConstraint(['product_details_id'], ['product_details.product_details_id'], ),
    sa.ForeignKeyConstraint(['renter_id'], ['renter.renter_id'], ),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_index(op.f('ix_policy_policy_id'), 'policy', ['policy_id'], unique=False)
    op.create_table('bill',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('installments', sa.Integer(), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('per_month', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.policy_id'], ),
    sa.PrimaryKeyConstraint('bill_id')
    )
    op.create_index(op.f('ix_bill_bill_id'), 'bill', ['bill_id'], unique=False)
    op.create_index(op.f('ix_bill_policy_id'), 'bill', ['policy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_policy_id'), table_name='bill')
    op.drop_index(op.f('ix_bill_bill_id'), table_name='bill')
    op.drop_table('bill')
    op.drop_index(op.f('ix_policy_policy_id'), table_name='policy')
    op.drop_table('policy')
    op.drop_index(op.f('ix_renter_renter_id'), table_name='renter')
    op.drop_table('renter')
    op.drop_index(op.f('ix_product_details_product_details_id'), table_name='product_details')
    op.drop_table('product_details')
    op.drop_index(op.f('ix_beneficiary_beneficiary_id'), table_name='beneficiary')
    op.drop_table('beneficiary')
    op.drop_index(op.f('ix_address_street'), table_name='address')
    op.drop_index(op.f('ix_address_number'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
